// DO NOT MODIFY FOR BASIC SUBMISSION
// scalastyle:off

package test.snake

import snake.game.{East, North, South, West}
import test.snake.SnakeRecord._

object SnakeTests {


  // ===1.1===

  val testStartCorrectly =
    SnakeTest("testStartCorrectly",
      List(
        TestFrame(0,
          """OO>A..
            |......""")))


  val testApplePos3 =
    SnakeTest("testApplePos3",
      List(
        TestFrame(3,
          """OO>...
            |A.....""")))


  val testApplePos8 =
    SnakeTest("testApplePos8",
      List(
        TestFrame(8,
          """OO>...
            |.....A""")))


  val testNoRoomForApple =
    SnakeTest("testNoRoomForApple",
      List(
        TestFrame(2,
          """OO>..A"""),
        TestFrame(2,
          """.OO>.A"""),
        TestFrame(2,
          """..OO>A"""),
        TestFrame(2,
          """..AOO>"""),
        TestFrame(2,
          """>.AOOO"""),
        TestFrame(2,
          """O>AOOO"""),
        TestFrame(2,
          """OO>OOO"""),
        TestFrame(2,
          GameOverDisplay()
        )))


  val testMove =
    SnakeTest("testMove",
      List(
        TestFrame(3,
          """OO>...
            |A....."""),
        TestFrame(3,
          """.OO>..
            |A....."""),
        TestFrame(3,
          """..OO>.
            |A....."""),
      ))


  val testIgnoreEatHead =
    SnakeTest("testIgnoreEatHead",
      List(
        TestFrame(5,
          """OO>...
            |..A..."""),
        TestFrame(5, List(ChangeDir(West())),
          """.OO>..
            |..A..."""),
        TestFrame(5, List(ChangeDir(West())),
          """..OO>.
            |..A...""")
      ))


  val testIgnoreEatHeadQuickSwitch =
    SnakeTest("testQuickSwitch",
      List(
        TestFrame(4,
          """OO>.
            |...A
            |...."""),
        TestFrame(4,
          """.OO>
            |...A
            |...."""),
        TestFrame(4, List(ChangeDir(North()), ChangeDir(West())),
          """..OO
            |...A
            |...^"""),
      ))

  val testIgnoreEatHeadQuickSwitch2 =
    SnakeTest("testQuickSwitch2",
      List(
        TestFrame(4,
          """OO>.
            |...A
            |...."""),
        TestFrame(4,
          """.OO>
            |...A
            |...."""),
        TestFrame(4, List(ChangeDir(West()), ChangeDir(North())),
          """..OO
            |...A
            |...^"""),
      ))


  val testChangeDirs =
    SnakeTest("testChangeDirs",
      List(
        TestFrame(2,
          """OO>.
            |.A..
            |....
            |...."""),
        TestFrame(2, List(ChangeDir(South())),
          """.OO.
            |.Av.
            |....
            |...."""),
        TestFrame(2,
          """..O.
            |.AO.
            |..v.
            |...."""),
        TestFrame(2, List(ChangeDir(West())),
          """....
            |.AO.
            |.<O.
            |...."""),
        TestFrame(2,
          """....
            |.A..
            |<OO.
            |...."""),
        TestFrame(2, List(ChangeDir(North())),
          """....
            |^A..
            |OO..
            |...."""),
        TestFrame(2,
          """^...
            |OA..
            |O...
            |...."""),
        TestFrame(2, List(ChangeDir(East())),
          """O>..
            |OA..
            |....
            |...."""),
        TestFrame(2,
          """OO>.
            |.A..
            |....
            |....""")))


  val testWrapAroundEast =
    SnakeTest("testWrapAroundEast",
      List(
        TestFrame(6,
          """OO>...
            |...A.."""),
        TestFrame(6,
          """.OO>..
            |...A.."""),
        TestFrame(6,
          """..OO>.
            |...A.."""),
        TestFrame(6,
          """...OO>
            |...A.."""),
        TestFrame(6,
          """>...OO
            |...A.."""),
        TestFrame(6,
          """O>...O
            |...A.."""),
        TestFrame(6,
          """OO>...
            |...A.."""),
        TestFrame(6,
          """.OO>..
            |...A.."""),
      ))


  val testWrapAroundSouth = SnakeTest("testWrapAroundSouth",
    List(
      TestFrame(2,
        """OO>.
          |.A..
          |....
          |...."""),
      TestFrame(2, List(ChangeDir(South())),
        """.OO.
          |.Av.
          |....
          |...."""),
      TestFrame(2,
        """..O.
          |.AO.
          |..v.
          |...."""),
      TestFrame(2,
        """....
          |.AO.
          |..O.
          |..v."""),
      TestFrame(2,
        """..v.
          |.A..
          |..O.
          |..O."""),
      TestFrame(2,
        """..O.
          |.Av.
          |....
          |..O."""),
      TestFrame(2,
        """..O.
          |.AO.
          |..v.
          |....""")))


  val testWrapAroundNorth =
    SnakeTest("testWrapAroundNorth",
      List(
        TestFrame(6,
          """OO>.
            |....
            |.A..
            |...."""),
        TestFrame(6, List(ChangeDir(North())),
          """.OO.
            |....
            |.A..
            |..^."""),
        TestFrame(6,
          """..O.
            |....
            |.A^.
            |..O."""),
        TestFrame(6,
          """....
            |..^.
            |.AO.
            |..O."""),
        TestFrame(6,
          """..^.
            |..O.
            |.AO.
            |...."""),
      ))


  val testWrapAroundWest = SnakeTest("testWrapAroundWest",
    List(
      TestFrame(2,
        """OO>.
          |.A..
          |....
          |...."""),
      TestFrame(2,
        """.OO>
          |.A..
          |....
          |...."""),
      TestFrame(2, List(ChangeDir(South())),
        """..OO
          |.A.v
          |....
          |...."""),
      TestFrame(2,
        """...O
          |.A.O
          |...v
          |...."""),
      TestFrame(2, List(ChangeDir(West())),
        """....
          |.A.O
          |..<O
          |...."""),
      TestFrame(2,
        """....
          |.A..
          |.<OO
          |...."""),
      TestFrame(2,
        """....
          |.A..
          |<OO.
          |...."""),
      TestFrame(2,
        """....
          |.A..
          |OO.<
          |...."""),
      TestFrame(2,
        """....
          |.A..
          |O.<O
          |...."""),
    ))


  val testGrow = SnakeTest("testGrow",
    List(
      TestFrame(1,
        """OO>.A.....
          |.........."""),
      TestFrame(1,
        """.OO>A.....
          |.........."""),
      TestFrame(10,
        """..OO>.....
          |...A......"""),
      TestFrame(10,
        """..OOO>....
          |...A......"""),
      TestFrame(10,
        """..OOOO>...
          |...A......"""),
      TestFrame(10,
        """..OOOOO>..
          |...A......"""),
      TestFrame(10,
        """...OOOOO>.
          |...A......"""),
      TestFrame(10,
        """....OOOOO>
          |...A......"""),
    ))


  val testGrowTwice = SnakeTest("testGrowTwice",
    List(
      TestFrame(0,
        """OO>A..........
          |.............."""),
      TestFrame(2,
        """.OO>.A........
          |.............."""),
      TestFrame(2,
        """.OOO>A........
          |.............."""),
      TestFrame(10,
        """.OOOO>........
          |.A............"""),
      TestFrame(10,
        """.OOOOO>.......
          |.A............"""),
      TestFrame(10,
        """.OOOOOO>......
          |.A............"""),
      TestFrame(10,
        """.OOOOOOO>.....
          |.A............"""),
      TestFrame(10,
        """.OOOOOOOO>....
          |.A............"""),
      TestFrame(10,
        """..OOOOOOOO>...
          |.A............"""),
      TestFrame(10,
        """...OOOOOOOO>..
          |.A............"""),
      TestFrame(10,
        """....OOOOOOOO>.
          |.A............"""),
    ))


  val testPreciselyDoesNotDie =
    SnakeTest("testPreciselyDoesNotDie",
      List(
        TestFrame(0,
          """OO>A..
            |......"""),
        TestFrame(3,
          """.OO>..
            |A....."""),
        TestFrame(3,
          """.OOO>.
            |A....."""),
        TestFrame(3,
          """.OOOO>
            |A....."""),
        TestFrame(3,
          """>OOOOO
            |A....."""),
        TestFrame(3,
          """O>OOOO
            |A....."""),
        TestFrame(3,
          """OO>OOO
            |A....."""),
        TestFrame(3,
          """OOO>OO
            |A....."""),
        TestFrame(3,
          """OOOO>O
            |A....."""),
        TestFrame(3,
          """OOOOO>
            |A....."""),
      ))


  val testGameOver = SnakeTest("testGameOver",
    List(
      TestFrame(0,
        """OO>A..
          |......
          |......"""),
      TestFrame(6,
        """.OO>..
          |...A..
          |......"""),
      TestFrame(6,
        """.OOO>.
          |...A..
          |......"""),
      TestFrame(6,
        """.OOOO>
          |...A..
          |......"""),
      TestFrame(6, List(ChangeDir(South())),
        """.OOOOO
          |...A.v
          |......"""),
      TestFrame(6, List(ChangeDir(West())),
        """..OOOO
          |...A<O
          |......"""),
      TestFrame(6, List(ChangeDir(North())),
        GameOverDisplay())
    ))

  val testNoEscapeGameOver = SnakeTest("testNoEscapeGameOver",
      List(
        TestFrame(0,
          """OO>A.
            |.....
            |.....
            |....."""),
        TestFrame(0,
          """AOO>.
            |.....
            |.....
            |....."""),
        TestFrame(0, List(ChangeDir(South())),
          """AOOO.
            |...v.
            |.....
            |....."""),
        TestFrame(0, List(ChangeDir(West())),
          """AOOO.
            |..<O.
            |.....
            |....."""),
        TestFrame(0, List(ChangeDir(North())),
          GameOverDisplay()),
        TestFrame(0, GameOverDisplay())))


  val testGame3x1 = SnakeTest("testGame3x1",
    List(
      TestFrame(0,
        """OO>"""),
      TestFrame(0,
        """>OO"""),
      TestFrame(0,
        """O>O"""),
      TestFrame(0,
        """OO>"""),
      TestFrame(0,
        """>OO"""),
      TestFrame(0,
        """O>O"""),
      TestFrame(0,
        """OO>""")))


  val testGame6x6 =
    SnakeTest("testGame6x6", List(
      TestFrame(2,
        """OO>..A
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """.OO>.A
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """..OO>A
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """..AOO>
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """>.AOOO
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """O>AOOO
          |......
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """OO>OOO
          |..A...
          |......
          |......
          |......
          |......"""),
      TestFrame(2, List(ChangeDir(South())),
        """OOOOOO
          |..vA..
          |......
          |......
          |......
          |......"""),
      TestFrame(2,
        """OOOOOO
          |..OA..
          |..v...
          |......
          |......
          |......"""),
      TestFrame(2, List(ChangeDir(West())),
        """OOOOOO
          |..OA..
          |.<O...
          |......
          |......
          |......"""),
      TestFrame(2, List(ChangeDir(North())),
        """OOOOOO
          |.^OA..
          |.OO...
          |......
          |......
          |......"""),
      TestFrame(2, List(ChangeDir(West())),
        """OOOOOO
          |<OOA..
          |.OO...
          |......
          |......
          |......"""),
      TestFrame(2,
        """OOOOOO
          |OOOA.<
          |.OO...
          |......
          |......
          |......"""),
      TestFrame(2,
        """OOO.OO
          |OOOA<O
          |.OO...
          |......
          |......
          |......"""),
      TestFrame(2,
        """OOO..O
          |OOO<OO
          |AOO...
          |......
          |......
          |......"""),
      TestFrame(2, List(ChangeDir(North())),
        """OOO^.O
          |OOOOOO
          |AOO...
          |......
          |......
          |......"""),
      TestFrame(2,
        """OOOO.O
          |OOOOOO
          |AOO...
          |......
          |......
          |...^.."""),
      TestFrame(2,
        """OOOO.O
          |OOOOOO
          |AOO...
          |......
          |...^..
          |...O.."""),
      TestFrame(2, List(ChangeDir(West())),
        """OOOO..
          |OOOOOO
          |AOO...
          |......
          |..<O..
          |...O.."""),
      TestFrame(2,
        """.OOO..
          |OOOOOO
          |AOO...
          |......
          |.<OO..
          |...O.."""),
      TestFrame(2,
        """..OO..
          |OOOOOO
          |AOO...
          |......
          |<OOO..
          |...O.."""),
      TestFrame(2, List(ChangeDir(North())),
        """...O..
          |OOOOOO
          |AOO...
          |^.....
          |OOOO..
          |...O.."""),
      TestFrame(2,
        """..AO..
          |OO.OOO
          |^OO...
          |O.....
          |OOOO..
          |...O.."""),
      TestFrame(2, List(ChangeDir(West())),
        """..AO..
          |OO.OOO
          |OOO..<
          |O.....
          |OOOO..
          |...O.."""),
      TestFrame(2,
        """..AO..
          |OO.OOO
          |OOO.<O
          |O.....
          |OOOO..
          |...O.."""),
      TestFrame(2, List(ChangeDir(South())),
        """..AO..
          |OO.OOO
          |OOO.OO
          |O...v.
          |OOOO..
          |...O.."""),
      TestFrame(2, List(ChangeDir(East())),
        """..AO..
          |OO.OOO
          |OO..OO
          |O...O>
          |OOOO..
          |...O.."""),
      TestFrame(2,
        GameOverDisplay()),
    ))


  val testGame6x3 = SnakeTest("testGame6x3",
    List(
      TestFrame(2,
        """OO>..A
          |......
          |......"""),
      TestFrame(2,
        """.OO>.A
          |......
          |......"""),
      TestFrame(2,
        """..OO>A
          |......
          |......"""),
      TestFrame(2,
        """..AOO>
          |......
          |......"""),
      TestFrame(2,
        """>.AOOO
          |......
          |......"""),
      TestFrame(2,
        """O>AOOO
          |......
          |......"""),
      TestFrame(2,
        """OO>OOO
          |..A...
          |......"""),
      TestFrame(2, List(ChangeDir(North())),
        """OOOOOO
          |..A...
          |..^..."""),
      TestFrame(2,
        """OOOOOO
          |..^A..
          |..O..."""),
      TestFrame(2, List(ChangeDir(West())),
        """OOOOOO
          |.<OA..
          |..O..."""),
      TestFrame(2,
        """OOOOOO
          |<OOA..
          |..O..."""),
      TestFrame(2,
        """OOOOOO
          |OOOA.<
          |..O..."""),
      TestFrame(2,
        """OOOOOO
          |OOOA<O
          |..O..."""),
      TestFrame(2,
        """OOO.OO
          |OOO<OO
          |.AO..."""),
      TestFrame(2, List(ChangeDir(South())),
        """OOO.OO
          |OOOOOO
          |.AOv.."""),
      TestFrame(2, List(ChangeDir(East())),
        """OOO.OO
          |OOOOOO
          |.AOO>."""),
      TestFrame(2,
        """OOO.OO
          |OOOOOO
          |.AOOO>"""),
      TestFrame(2,
        """OOO..O
          |OOOOOO
          |>AOOOO"""),
      TestFrame(2,
        """OOO..A
          |OOOOOO
          |O>OOOO"""),
      TestFrame(2,
        GameOverDisplay())))


  val testGame10x7 = SnakeTest("testGame10x7",
    List(
      TestFrame(2,
        """OO>..A....
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """.OO>.A....
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..OO>A....
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..AOO>....
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..AOOO>...
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..AOOOO>..
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..AOOOOO>.
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """..A.OOOOO>
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """>.A..OOOOO
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """O>A...OOOO
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """OO>..A.OOO
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """OOO>.A.OOO
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """OOOO>A.OOO
          |..........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """OOOOO>.OOO
          |.A........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2,
        """OOOOOO>OOO
          |.A........
          |..........
          |..........
          |..........
          |..........
          |.........."""),
      TestFrame(2, List(ChangeDir(North())),
        """OOOOOOOOOO
          |.A........
          |..........
          |..........
          |..........
          |..........
          |......^..."""),
      TestFrame(2,
        """OOOOOOOOOO
          |.A........
          |..........
          |..........
          |..........
          |......^...
          |......O..."""),
      TestFrame(2, List(ChangeDir(East())),
        """OOOOOOO.OO
          |.A........
          |..........
          |..........
          |..........
          |......O>..
          |......O..."""),
      TestFrame(2,
        """OOOOOOO..O
          |.A........
          |..........
          |..........
          |..........
          |......OO>.
          |......O..."""),
      TestFrame(2,
        """OOOOOOO...
          |.A........
          |..........
          |..........
          |..........
          |......OOO>
          |......O..."""),
      TestFrame(2,
        """.OOOOOO...
          |.A........
          |..........
          |..........
          |..........
          |>.....OOOO
          |......O..."""),
      TestFrame(2,
        """..OOOOO...
          |.A........
          |..........
          |..........
          |..........
          |O>....OOOO
          |......O..."""),
      TestFrame(2,
        """...OOOO...
          |.A........
          |..........
          |..........
          |..........
          |OO>...OOOO
          |......O..."""),
      TestFrame(2,
        """....OOO...
          |.A........
          |..........
          |..........
          |..........
          |OOO>..OOOO
          |......O..."""),
      TestFrame(2,
        """.....OO...
          |.A........
          |..........
          |..........
          |..........
          |OOOO>.OOOO
          |......O..."""),
      TestFrame(2, List(ChangeDir(North())),
        """......O...
          |.A........
          |..........
          |..........
          |....^.....
          |OOOOO.OOOO
          |......O..."""),
      TestFrame(2,
        """..........
          |.A........
          |..........
          |....^.....
          |....O.....
          |OOOOO.OOOO
          |......O..."""),
      TestFrame(2,
        """..........
          |.A........
          |....^.....
          |....O.....
          |....O.....
          |OOOOO.OOOO
          |.........."""),
      TestFrame(2,
        """..........
          |.A..^.....
          |....O.....
          |....O.....
          |....O.....
          |OOOOO..OOO
          |.........."""),
      TestFrame(2, List(ChangeDir(West())),
        """..........
          |.A.<O.....
          |....O.....
          |....O.....
          |....O.....
          |OOOOO...OO
          |.........."""),
      TestFrame(2,
        """..........
          |.A<OO.....
          |....O.....
          |....O.....
          |....O.....
          |OOOOO....O
          |.........."""),
      TestFrame(2,
        """..A.......
          |.<OOO.....
          |....O.....
          |....O.....
          |....O.....
          |OOOOO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |<OOOO.....
          |....O.....
          |....O.....
          |....O.....
          |OOOOO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO....<
          |....O.....
          |....O.....
          |....O.....
          |OOOOO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO...<O
          |....O.....
          |....O.....
          |....O.....
          |OOOOO.....
          |.........."""),
      TestFrame(2, List(ChangeDir(South())),
        """..A.......
          |OOOOO...OO
          |....O...v.
          |....O.....
          |....O.....
          |.OOOO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO...OO
          |....O...O.
          |....O...v.
          |....O.....
          |..OOO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO...OO
          |....O...O.
          |....O...O.
          |....O...v.
          |...OO.....
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO...OO
          |....O...O.
          |....O...O.
          |....O...O.
          |....O...v.
          |.........."""),
      TestFrame(2,
        """..A.......
          |OOOOO...OO
          |....O...O.
          |....O...O.
          |....O...O.
          |........O.
          |........v."""),
      TestFrame(2,
        """..A.....v.
          |OOOOO...OO
          |....O...O.
          |....O...O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2, List(ChangeDir(West())),
        """..A....<O.
          |OOOOO...OO
          |....O...O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """..A...<OO.
          |OOOOO...OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """..A..<OOO.
          |OOOO....OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """..A.<OOOO.
          |OOO.....OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """..A<OOOOO.
          |OO......OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """..<OOOOOOA
          |O.......OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2,
        """.<OOOOOOOA
          |O.......OO
          |........O.
          |........O.
          |........O.
          |........O.
          |........O."""),
      TestFrame(2, List(ChangeDir(North())),
        """.OOOOOOOOA
          |O.......OO
          |........O.
          |........O.
          |........O.
          |........O.
          |.^......O."""),
      TestFrame(2,
        """.OOOOOOOOA
          |O.......OO
          |........O.
          |........O.
          |........O.
          |.^......O.
          |.O......O."""),
      TestFrame(2,
        """.OOOOOOOOA
          |........OO
          |........O.
          |........O.
          |.^......O.
          |.O......O.
          |.O......O."""),
      TestFrame(2,
        """.OOOOOOOOA
          |........O.
          |........O.
          |.^......O.
          |.O......O.
          |.O......O.
          |.O......O."""),
      TestFrame(2,
        """.OOOOOOOOA
          |..........
          |.^......O.
          |.O......O.
          |.O......O.
          |.O......O.
          |.O......O."""),
      TestFrame(2,
        """.OOOOOOOOA
          |.^........
          |.O........
          |.O......O.
          |.O......O.
          |.O......O.
          |.O......O."""),
      TestFrame(2,
        GameOverDisplay())))





  val testNoReverseMode = SnakeTest("TestNoReverseMode",
    List(
      TestFrame(2,
        """OO>.
          |.A.."""),
      TestFrame(2,
        """.OO>
          |.A.."""),
      TestFrame(2,
        """>.OO
          |.A.."""),
      TestFrame(2,
        """O>.O
          |.A.."""),
      TestFrame(2, List(ReverseGame(true)),
        """OO>.
          |.A.."""),
      TestFrame(2,
        """.OO>
          |.A.."""),
      TestFrame(2,
        """>.OO
          |.A.."""),
      TestFrame(2, List(ReverseGame(false)),
        """O>.O
          |.A.."""),
      TestFrame(2,
        """OO>.
          |.A.."""),
      TestFrame(2,
        """.OO>
          |.A.."""),
      TestFrame(2, List(ReverseGame(true)),
        """>.OO
          |.A.."""),
      TestFrame(2,
        """O>.O
          |.A.."""),
      TestFrame(2,
        """OO>.
          |.A.."""),
      TestFrame(2, List(ReverseGame(false)),
        """.OO>
          |.A.."""),
    ))

  // ===1.3==

  val testReverseSimple = SnakeTest("testReverseSimple",
    List(
      TestFrame(2,
        """OO>..
          |A....
          |....."""),
      TestFrame(2,
        """.OO>.
          |A....
          |....."""),
      TestFrame(2,
        """..OO>
          |A....
          |....."""),
      TestFrame(2, List(ReverseGame(true)),
        """.OO>.
          |A....
          |....."""),
      TestFrame(2,
        """OO>..
          |A....
          |....."""),
    ))

  val testReversePastStart = SnakeTest("testReversePastStart",
    List(
      TestFrame(2,
        """OO>..
          |A...."""),
      TestFrame(2,
        """.OO>.
          |A...."""),
      TestFrame(2,
        """..OO>
          |A...."""),
      TestFrame(2,
        """>..OO
          |A...."""),
      TestFrame(2, List(ReverseGame(true)),
        """..OO>
          |A...."""),
      TestFrame(2,
        """.OO>.
          |A...."""),
      TestFrame(2,
        """OO>..
          |A....""")))

  val testReverseGameOver = SnakeTest("testReverseGameOver",
    List(
      TestFrame(2,
        """OO>..
          |A...."""),
      TestFrame(2,
        """.OO>.
          |A...."""),
      TestFrame(2,
        """..OO>
          |A...."""),
      TestFrame(2, List(ChangeDir(North())),
        """...OO
          |A...^"""),
      TestFrame(2,
        GameOverDisplay()),
      TestFrame(2,
        GameOverDisplay()),
      TestFrame(2,
        GameOverDisplay()),
      TestFrame(2, List(ReverseGame(true)),
        """...OO
          |A...^"""),
      TestFrame(2,
        """..OO>
          |A...."""),
      TestFrame(2,
        """.OO>.
          |A...."""),
      TestFrame(2,
        """OO>..
          |A...."""),
    ))

  val testChangeThePast = SnakeTest("testChangeThePast",
    List(
      TestFrame(2,
        """OO>..
          |A....
          |....."""),
      TestFrame(2,
        """.OO>.
          |A....
          |....."""),
      TestFrame(2,
        """..OO>
          |A....
          |....."""),
      TestFrame(2,
        """>..OO
          |A....
          |....."""),
      TestFrame(2, List(ReverseGame(true)),
        """..OO>
          |A....
          |....."""),
      TestFrame(2,
        """.OO>.
          |A....
          |....."""),
      TestFrame(2,
        """OO>..
          |A....
          |....."""),
      TestFrame(2, List(ReverseGame(false), ChangeDir(South())),
        """.OO..
          |A.v..
          |....."""),
      TestFrame(2, List(ChangeDir(West())),
        """..O..
          |A<O..
          |....."""),
      TestFrame(4,
        """....A
          |<OO..
          |.....""")))


  val testReverseLong = SnakeTest("testReverseLong",
    List(
      TestFrame(2,
        """OO>..
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(2,
        """.OO>.
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(2, List(ChangeDir(South()), ChangeDir(West())),
        """..OO.
          |A..v.
          |.....
          |.....
          |....."""),
      TestFrame(2, List(ChangeDir(West())),
        """...O.
          |A.<O.
          |.....
          |.....
          |....."""),
      TestFrame(2,
        """.....
          |A<OO.
          |.....
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |<OO..
          |.....
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |OOO.<
          |.....
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |OOO<O
          |.....
          |.....
          |....."""),
      TestFrame(4, List(ChangeDir(North())),
        """...^A
          |OOOOO
          |.....
          |.....
          |....."""),
      TestFrame(2, List(ChangeDir(East())),
        """..AO>
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(2,
        """>.AOO
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(2,
        """O>AOO
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(4,
        """OO>OO
          |OO.OO
          |...A.
          |.....
          |....."""),
      TestFrame(4,
        GameOverDisplay()),
      TestFrame(4,
        GameOverDisplay()),
      TestFrame(4, List(ReverseGame(true)),
        """OO>OO
          |OO.OO
          |...A.
          |.....
          |....."""),
      TestFrame(4,
        """O>AOO
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(4, List(ReverseGame(false)),
        """OO>OO
          |OO.OO
          |...A.
          |.....
          |....."""),
      TestFrame(4, List(ChangeDir(South())),
        """OOOOO
          |OOvOO
          |...A.
          |.....
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |..vA.
          |.....
          |....."""),
      TestFrame(2, List(ChangeDir(East())),
        """OOOOO
          |OOOOO
          |..O>A
          |.....
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |..OO>
          |..A..
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |>.OOO
          |..A..
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |O>OOO
          |..A..
          |....."""),
      TestFrame(4, List(ChangeDir(South()), ChangeDir(East())),
        GameOverDisplay()),
      TestFrame(4,
        GameOverDisplay()),
      TestFrame(4, List(ReverseGame(true)),
        """OOOOO
          |OOOOO
          |O>OOO
          |..A..
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |>.OOO
          |..A..
          |....."""),
      TestFrame(4, List(ReverseGame(false)),
        """OOOOO
          |OOOOO
          |O>OOO
          |..A..
          |....."""),
      TestFrame(4, List(ChangeDir(South())),
        """OOOOO
          |OOOOO
          |OOOOO
          |.vA..
          |....."""),
      TestFrame(2, List(ChangeDir(East())),
        """OOOOO
          |OOOOO
          |OOOOO
          |.O>.A
          |....."""),
      TestFrame(2,
        """OOOOO
          |OOOOO
          |OOOOO
          |.OO>A
          |....."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |OOOOO
          |.OOO>
          |...A."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |OOOOO
          |>OOOO
          |...A."""),
      TestFrame(4, List(ChangeDir(South())),
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |v..A."""),
      TestFrame(4, List(ChangeDir(East())),
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |O>.A."""),
      TestFrame(4,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OO>A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OOO>A"""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OOOO>"""),
      TestFrame(0,
        GameOverDisplay()),
      TestFrame(0,
        GameOverDisplay()),
      TestFrame(0,
        GameOverDisplay()),
      TestFrame(0, List(ReverseGame(true)),
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OOOO>"""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OOO>A"""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |OO>A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |O>.A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |OOOOO
          |v..A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |>OOOO
          |...A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |.OOO>
          |...A."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |.OO>A
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |.O>.A
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |OOOOO
          |.vA..
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |O>OOO
          |..A..
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |>.OOO
          |..A..
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |..OO>
          |..A..
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |..O>A
          |.....
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOOOO
          |..vA.
          |.....
          |....."""),
      TestFrame(0,
        """OOOOO
          |OOvOO
          |...A.
          |.....
          |....."""),
      TestFrame(0,
        """OO>OO
          |OO.OO
          |...A.
          |.....
          |....."""),
      TestFrame(0,
        """O>AOO
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """>.AOO
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """..AO>
          |OO.OO
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """...^A
          |OOOOO
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """....A
          |OOO<O
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """....A
          |OOO.<
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """....A
          |<OO..
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """.....
          |A<OO.
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """...O.
          |A.<O.
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """..OO.
          |A..v.
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """.OO>.
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """OO>..
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """OO>..
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(0, List(ReverseGame(false)),
        """.OO>.
          |A....
          |.....
          |.....
          |....."""),
      TestFrame(0, List(ChangeDir(South())),
        """..OO.
          |A..v.
          |.....
          |.....
          |....."""),
      TestFrame(0, List(ChangeDir(West())),
        """...O.
          |A.<O.
          |.....
          |.....
          |....."""),
      TestFrame(0,
        """.....
          |A<OO.
          |.....
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |<OO..
          |.....
          |.....
          |....."""),
      TestFrame(4, List(ChangeDir(South())),
        """....A
          |OOO..
          |v....
          |.....
          |....."""),
      TestFrame(4, List(ChangeDir(East())),
        """....A
          |OOO..
          |O>...
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |OOO..
          |OO>..
          |.....
          |....."""),
      TestFrame(4,
        """....A
          |OO...
          |OOO>.
          |.....
          |....."""),
    ))


}
